# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be98dfae47475a7cac0e1c391a33e152139ae15e8f8c79852c7048fde95c0418ff3a3db4e399fcdff7e65d5be7400dd514d67d120d95203c123d2034f83493af

test:
  secret_key_base: 810949026fb357e7d537234d19e98b80231652b0b50cbd8ca273fa505685f6dab47d2122a2332b0f1d5df61c1c1c94f02e1a71e19803146a14de61bb22198d2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
